### PR TITLE
Rename `footer` to match expected casing

### PR DESCRIPTION
**Pull request by joneshf**
#### What does this PR do?
- On case-sensitive file systems (e.g. Linux) the casing of `footer` was breaking the `start` script. We changed it to `Footer`, and things started working again. This should still work on case-insensitive file systems though (e.g. macOS and Windows).

#### Description of Task to be completed?
- Fix the `start` script.

#### How should this be manually tested?
- Run `npm run start` to validate it works.

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
- N/A

#### Pull Request Type (check one)
- [ ] Feature
- [x] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [x] New code has been scanned for eslint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guildlines

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by joneshf** [comment]
I'm happy to go either way, but it looks like it's more than just `src/components/Footer` and `src/components/Navigation`.

Looks like the following would need to be addressed:
* `src/components/Footer` -> `src/components/footer`
* `src/components/Navigation` -> `src/components/navigation`
* `src/components/profile/Button` -> `src/components/profile/button`
* `src/components/ui/GetInvolved` -> `src/components/ui/getInvolved`
* `src/components/ui/MediaList` -> `src/components/ui/mediaList`
* `src/components/ui/Media` -> `src/components/ui/media`

Along with updating all of the imports to match the casing. Does that seem right?

**Comment by Easybuoy** [comment]
> ith updating all o

Wow, there's a lot, Okay let's fix the conflict for now. We would have to address it later

**Comment by joneshf** [comment]
K. I'll push something in a few.

**Comment by joneshf** [comment]
Also, i'm down to do the work. Just lemme know.

**Comment by Easybuoy** [comment]
> Also, i'm down to do the work. Just lemme know.

You can do it and raise another PR

**Comment by joneshf** [comment]
Sounds good! Thanks for the review!

**Pull request merged**
