### PR TITLE
Added breakpoints and media query utility

### PR DESCRIPTION
**Pull request by samakintunde37**
#### What does this PR do?
- Includes definition for breakpoints in the `src/constants` folder.
- Adds a utility function to add media queries in styled component's styles.

#### Description of Task to be completed?
- Ensure ease of use of writing media queries in a way that's more synonymous to how styled components work and increase consistency with use of breakpoints as constants.

#### How should this be manually tested?
- Add it to a styled component as seen in the screenshot below

#### What are the relevant Trello Card stories?
- [ Trello Card Item ](https://trello.com/c/PzcBfpXR)

#### Pull Request Type (check one)
- [ ] Feature
- [ ] Bug Fixes
- [x] Chore

#### Developer Checklist
- [x] New code has been scanned for eslint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)
breakpoints

### CODE REVIEW

**Comment by Easybuoy** [comment]
Can you raise the Pull Request again against the `development` branch

**Comment by samakintunde37** [comment]
Okay, done.

**Comment by samakintunde37** [comment]
@Easybuoy and I thought the breakpoints were too loosely apart and we'd have another in between mobile and tablet. I was thinking somewhere around 480px. Most mobile phones fall in between 300px and 480px. Some phablets do occupy sizes between 480px - 768px. What do you think?

**Comment by samakintunde37** [comment]
Okay, this looks fine. I'll get on it!

**Pull request merged**
